#!/usr/bin/env bash
# Configure HAproxy to automatically redirect HTTP traffic to HTTPS

global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/yourdomain.com/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend web_servers

backend web_servers
    server web-01 127.0.0.1:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /stats
    stats realm Haproxy\ Statistics
    stats auth username:password
