#!/usr/bin/env bash
# transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

scp -i "$path_ssh_key" -o "StrictHostKeyChecking no" "$path_file" "$username@$ip":~/

if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
