#!/bin/bash
# have a custom 404 page

if ! command -v nginx &> /dev/null; then
    # If not installed, install Nginx
    sudo apt-get update > /dev/null 2>&1
    sudo apt-get install -y nginx > /dev/null 2>&1
fi

echo "<html><body>Ceci n'est pas une page</body></html>" | sudo tee /var/www/html/custom_404.html > /dev/null 2>&1
echo "server {
    listen 80;
    server_name localhost;

    error_page 404 /custom_404.html;

    location / {
        root /var/www/html;
        index index.html;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null 2>&1

sudo /etc/init.d/nginx restart > /dev/null 2>&1

echo "Nginx configured for custom 404 page successfully!"
