#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx
hostname=$(hostname)
echo "add_header X-Served-By $hostname;" | sudo tee /etc/nginx/sites-available/custom_header
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
