#!/usr/bin/env bash
# same as task 0 but shorter
apt-get update
apt-get install -y nginx
echo "server { listen 80; server_name _; location / { root /usr/share/nginx/html; index index.html index.htm; }}" > /etc/nginx/sites-available/default
nginx -t
systemctl restart nginx
