#!/bin/bash

apt-get update
apt-get install -y nginx
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
echo "server {
    listen 8080;
    server_name _;

    location / {
        # Your configuration for handling requests goes here
        # Example: root /var/www/html;
        #          index index.html index.htm;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
