#!/usr/bin/env bash

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
nginx -t
if [ $? -eq 0 ]; then
    service nginx reload
    echo "Nginx configuration reloaded successfully."
else
    echo "Nginx configuration test failed. Please check your configuration."
fi
